/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthAppSomeRouteImport } from './routes/_auth.app/some-route'
import { Route as AuthAppLayoutImport } from './routes/_auth.app/_layout'

// Create Virtual Routes

const AuthAppImport = createFileRoute('/_auth/app')()

// Create/Update Routes

const AuthAppRoute = AuthAppImport.update({
  id: '/_auth/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AuthAppSomeRouteRoute = AuthAppSomeRouteImport.update({
  id: '/some-route',
  path: '/some-route',
  getParentRoute: () => AuthAppRoute,
} as any)

const AuthAppLayoutRoute = AuthAppLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthAppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppImport
      parentRoute: typeof rootRoute
    }
    '/_auth/app/_layout': {
      id: '/_auth/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppLayoutImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/some-route': {
      id: '/_auth/app/some-route'
      path: '/some-route'
      fullPath: '/app/some-route'
      preLoaderRoute: typeof AuthAppSomeRouteImport
      parentRoute: typeof AuthAppImport
    }
  }
}

// Create and export the route tree

interface AuthAppRouteChildren {
  AuthAppLayoutRoute: typeof AuthAppLayoutRoute
  AuthAppSomeRouteRoute: typeof AuthAppSomeRouteRoute
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppLayoutRoute: AuthAppLayoutRoute,
  AuthAppSomeRouteRoute: AuthAppSomeRouteRoute,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

export interface FileRoutesByFullPath {
  '/app': typeof AuthAppLayoutRoute
  '/app/some-route': typeof AuthAppSomeRouteRoute
}

export interface FileRoutesByTo {
  '/app': typeof AuthAppLayoutRoute
  '/app/some-route': typeof AuthAppSomeRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth/app': typeof AuthAppRouteWithChildren
  '/_auth/app/_layout': typeof AuthAppLayoutRoute
  '/_auth/app/some-route': typeof AuthAppSomeRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/app/some-route'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/app/some-route'
  id: '__root__' | '/_auth/app' | '/_auth/app/_layout' | '/_auth/app/some-route'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth/app"
      ]
    },
    "/_auth/app": {
      "filePath": "_auth.app",
      "children": [
        "/_auth/app/_layout",
        "/_auth/app/some-route"
      ]
    },
    "/_auth/app/_layout": {
      "filePath": "_auth.app/_layout.tsx",
      "parent": "/_auth/app"
    },
    "/_auth/app/some-route": {
      "filePath": "_auth.app/some-route.tsx",
      "parent": "/_auth/app"
    }
  }
}
ROUTE_MANIFEST_END */
