/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthAppRouteImport } from './routes/_auth.app/route'
import { Route as AuthAppIndexImport } from './routes/_auth.app/index'
import { Route as AuthAppSomeRouteImport } from './routes/_auth.app/some-route'

// Create/Update Routes

const AuthAppRouteRoute = AuthAppRouteImport.update({
  id: '/_auth/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AuthAppIndexRoute = AuthAppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

const AuthAppSomeRouteRoute = AuthAppSomeRouteImport.update({
  id: '/some-route',
  path: '/some-route',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/app/some-route': {
      id: '/_auth/app/some-route'
      path: '/some-route'
      fullPath: '/app/some-route'
      preLoaderRoute: typeof AuthAppSomeRouteImport
      parentRoute: typeof AuthAppRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexImport
      parentRoute: typeof AuthAppRouteImport
    }
  }
}

// Create and export the route tree

interface AuthAppRouteRouteChildren {
  AuthAppSomeRouteRoute: typeof AuthAppSomeRouteRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppSomeRouteRoute: AuthAppSomeRouteRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/app': typeof AuthAppRouteRouteWithChildren
  '/app/some-route': typeof AuthAppSomeRouteRoute
  '/app/': typeof AuthAppIndexRoute
}

export interface FileRoutesByTo {
  '/app/some-route': typeof AuthAppSomeRouteRoute
  '/app': typeof AuthAppIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/app/some-route': typeof AuthAppSomeRouteRoute
  '/_auth/app/': typeof AuthAppIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/app/some-route' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/app/some-route' | '/app'
  id: '__root__' | '/_auth/app' | '/_auth/app/some-route' | '/_auth/app/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth/app"
      ]
    },
    "/_auth/app": {
      "filePath": "_auth.app/route.tsx",
      "children": [
        "/_auth/app/some-route",
        "/_auth/app/"
      ]
    },
    "/_auth/app/some-route": {
      "filePath": "_auth.app/some-route.tsx",
      "parent": "/_auth/app"
    },
    "/_auth/app/": {
      "filePath": "_auth.app/index.tsx",
      "parent": "/_auth/app"
    }
  }
}
ROUTE_MANIFEST_END */
